# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History_bill.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding:0 ;\n"
"    margin:0 ;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: ;\n"
"background-image: url(:/images/1a800x6001.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(750, 50))
        self.navbar.setMaximumSize(QtCore.QSize(800, 50))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #1e1e2f;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  rgb(220, 165, 50);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Hlayout_1 = QtWidgets.QHBoxLayout()
        self.Hlayout_1.setObjectName("Hlayout_1")
        self.label_home = QtWidgets.QPushButton(self.navbar)
        self.label_home.setMinimumSize(QtCore.QSize(50, 50))
        self.label_home.setObjectName("label_home")
        self.Hlayout_1.addWidget(self.label_home)
        self.arrow1 = QtWidgets.QLabel(self.navbar)
        self.arrow1.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow1.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow1.setText("")
        self.arrow1.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow1.setScaledContents(True)
        self.arrow1.setObjectName("arrow1")
        self.Hlayout_1.addWidget(self.arrow1)
        self.label_detail = QtWidgets.QPushButton(self.navbar)
        self.label_detail.setMinimumSize(QtCore.QSize(50, 50))
        self.label_detail.setObjectName("label_detail")
        self.Hlayout_1.addWidget(self.label_detail)
        self.arrow2 = QtWidgets.QLabel(self.navbar)
        self.arrow2.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow2.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow2.setText("")
        self.arrow2.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow2.setScaledContents(True)
        self.arrow2.setObjectName("arrow2")
        self.Hlayout_1.addWidget(self.arrow2)
        self.label_seats = QtWidgets.QPushButton(self.navbar)
        self.label_seats.setMinimumSize(QtCore.QSize(50, 50))
        self.label_seats.setObjectName("label_seats")
        self.Hlayout_1.addWidget(self.label_seats)
        self.arrow3 = QtWidgets.QLabel(self.navbar)
        self.arrow3.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow3.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow3.setText("")
        self.arrow3.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow3.setScaledContents(True)
        self.arrow3.setObjectName("arrow3")
        self.Hlayout_1.addWidget(self.arrow3)
        self.label_payment = QtWidgets.QPushButton(self.navbar)
        self.label_payment.setMinimumSize(QtCore.QSize(50, 50))
        self.label_payment.setObjectName("label_payment")
        self.Hlayout_1.addWidget(self.label_payment)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Hlayout_1.addItem(spacerItem)
        self.label_username = QtWidgets.QPushButton(self.navbar)
        self.label_username.setMinimumSize(QtCore.QSize(50, 50))
        self.label_username.setObjectName("label_username")
        self.Hlayout_1.addWidget(self.label_username)
        self.horizontalLayout_4.addLayout(self.Hlayout_1)
        self.verticalLayout.addWidget(self.navbar)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_qrcode = QtWidgets.QLabel(self.frame)
        self.label_qrcode.setGeometry(QtCore.QRect(30, 60, 151, 31))
        self.label_qrcode.setStyleSheet("color: rgb(63, 63, 63);\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13pt;\n"
"    font-weight: bold;")
        self.label_qrcode.setObjectName("label_qrcode")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 90, 221, 221))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.isi_qrcode = QtWidgets.QLabel(self.frame_2)
        self.isi_qrcode.setGeometry(QtCore.QRect(20, 20, 180, 180))
        self.isi_qrcode.setMinimumSize(QtCore.QSize(180, 180))
        self.isi_qrcode.setMaximumSize(QtCore.QSize(180, 180))
        self.isi_qrcode.setStyleSheet("border: 1px solid;")
        self.isi_qrcode.setText("")
        self.isi_qrcode.setObjectName("isi_qrcode")
        self.bg_gradient1 = QtWidgets.QLabel(self.frame)
        self.bg_gradient1.setGeometry(QtCore.QRect(20, 60, 221, 31))
        self.bg_gradient1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));")
        self.bg_gradient1.setText("")
        self.bg_gradient1.setObjectName("bg_gradient1")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(270, 60, 491, 431))
        self.frame_3.setStyleSheet("#frame_3 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-right-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"color: black;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 10px;\n"
"    padding: 4px 10px;\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgb(230, 140, 45); /* Efek tambahan agar terlihat jelas */\n"
"    color: white;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.bg_gradient2 = QtWidgets.QLabel(self.frame_3)
        self.bg_gradient2.setGeometry(QtCore.QRect(-4, -8, 41, 441))
        self.bg_gradient2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.506, y1:0.994318, x2:0.488, y2:0, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));")
        self.bg_gradient2.setText("")
        self.bg_gradient2.setObjectName("bg_gradient2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 80, 251, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.VLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.VLayout_2.setContentsMargins(0, 0, 0, 0)
        self.VLayout_2.setObjectName("VLayout_2")
        self.isi_nomorpesan = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.isi_nomorpesan.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.isi_nomorpesan.setText("")
        self.isi_nomorpesan.setObjectName("isi_nomorpesan")
        self.VLayout_2.addWidget(self.isi_nomorpesan)
        self.isi_nomorVA = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.isi_nomorVA.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.isi_nomorVA.setText("")
        self.isi_nomorVA.setObjectName("isi_nomorVA")
        self.VLayout_2.addWidget(self.isi_nomorVA)
        self.isi_filmdipilih = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.isi_filmdipilih.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.isi_filmdipilih.setText("")
        self.isi_filmdipilih.setObjectName("isi_filmdipilih")
        self.VLayout_2.addWidget(self.isi_filmdipilih)
        self.isi_kursidipilih = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.isi_kursidipilih.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.isi_kursidipilih.setText("")
        self.isi_kursidipilih.setObjectName("isi_kursidipilih")
        self.VLayout_2.addWidget(self.isi_kursidipilih)
        self.isi_nomorstudio = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.isi_nomorstudio.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.isi_nomorstudio.setObjectName("isi_nomorstudio")
        self.VLayout_2.addWidget(self.isi_nomorstudio)
        self.isi_timefilm = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.isi_timefilm.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.isi_timefilm.setText("")
        self.isi_timefilm.setObjectName("isi_timefilm")
        self.VLayout_2.addWidget(self.isi_timefilm)
        self.isi_totalpayment = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.isi_totalpayment.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.isi_totalpayment.setText("")
        self.isi_totalpayment.setObjectName("isi_totalpayment")
        self.VLayout_2.addWidget(self.isi_totalpayment)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 151, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VLayout_1.setContentsMargins(0, 0, 0, 0)
        self.VLayout_1.setObjectName("VLayout_1")
        self.label_nopesan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_nopesan.setObjectName("label_nopesan")
        self.VLayout_1.addWidget(self.label_nopesan)
        self.label_paymentmethod = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_paymentmethod.setObjectName("label_paymentmethod")
        self.VLayout_1.addWidget(self.label_paymentmethod)
        self.label_filmdipilih = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_filmdipilih.setObjectName("label_filmdipilih")
        self.VLayout_1.addWidget(self.label_filmdipilih)
        self.label_kursidipilih = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_kursidipilih.setObjectName("label_kursidipilih")
        self.VLayout_1.addWidget(self.label_kursidipilih)
        self.label_studio = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_studio.setObjectName("label_studio")
        self.VLayout_1.addWidget(self.label_studio)
        self.label_time = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_time.setObjectName("label_time")
        self.VLayout_1.addWidget(self.label_time)
        self.label_totalpayment = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_totalpayment.setObjectName("label_totalpayment")
        self.VLayout_1.addWidget(self.label_totalpayment)
        self.label_pembuka2 = QtWidgets.QLabel(self.frame_3)
        self.label_pembuka2.setGeometry(QtCore.QRect(60, 50, 171, 16))
        self.label_pembuka2.setObjectName("label_pembuka2")
        self.label_tanggaltransaksi = QtWidgets.QLabel(self.frame_3)
        self.label_tanggaltransaksi.setGeometry(QtCore.QRect(300, 50, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_tanggaltransaksi.setFont(font)
        self.label_tanggaltransaksi.setStyleSheet("border:1px solid;\n"
"border-color: black;")
        self.label_tanggaltransaksi.setObjectName("label_tanggaltransaksi")
        self.label_pembuka1 = QtWidgets.QLabel(self.frame_3)
        self.label_pembuka1.setGeometry(QtCore.QRect(60, 30, 231, 20))
        self.label_pembuka1.setObjectName("label_pembuka1")
        self.label_penutup = QtWidgets.QLabel(self.frame_3)
        self.label_penutup.setGeometry(QtCore.QRect(60, 360, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_penutup.setFont(font)
        self.label_penutup.setObjectName("label_penutup")
        self.tombol_kembali = QtWidgets.QPushButton(self.frame_3)
        self.tombol_kembali.setGeometry(QtCore.QRect(370, 380, 80, 30))
        self.tombol_kembali.setMinimumSize(QtCore.QSize(80, 30))
        self.tombol_kembali.setMaximumSize(QtCore.QSize(80, 30))
        self.tombol_kembali.setStyleSheet("\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.tombol_kembali.setObjectName("tombol_kembali")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(270, 20, 491, 31))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_ticketing = QtWidgets.QLabel(self.frame_4)
        self.label_ticketing.setGeometry(QtCore.QRect(0, 0, 491, 31))
        self.label_ticketing.setStyleSheet("color: rgb(254, 180, 80);\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13pt;\n"
"    font-weight: bold;")
        self.label_ticketing.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ticketing.setObjectName("label_ticketing")
        self.bg_gradient1.raise_()
        self.frame_2.raise_()
        self.label_qrcode.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Absolute Cinema"))
        self.label_home.setText(_translate("MainWindow", "HOME"))
        self.label_detail.setText(_translate("MainWindow", "DETAIL"))
        self.label_seats.setText(_translate("MainWindow", "SEATS"))
        self.label_payment.setText(_translate("MainWindow", "PAYMENT"))
        self.label_username.setText(_translate("MainWindow", "USER_NAME"))
        self.label_qrcode.setText(_translate("MainWindow", "Qr Code"))
        self.isi_nomorstudio.setText(_translate("MainWindow", "1"))
        self.label_nopesan.setText(_translate("MainWindow", "Nomor pemesanan   :"))
        self.label_paymentmethod.setText(_translate("MainWindow", "Payment   VA           :"))
        self.label_filmdipilih.setText(_translate("MainWindow", "Film yang dipilih        :"))
        self.label_kursidipilih.setText(_translate("MainWindow", "Kursi yang dipilih      :"))
        self.label_studio.setText(_translate("MainWindow", "Studio                       :"))
        self.label_time.setText(_translate("MainWindow", "Time                         :"))
        self.label_totalpayment.setText(_translate("MainWindow", "Total Payment         :"))
        self.label_pembuka2.setText(_translate("MainWindow", "Berikut rincian pemesanan Anda :"))
        self.label_tanggaltransaksi.setText(_translate("MainWindow", "isi_tanggalpesan"))
        self.label_pembuka1.setText(_translate("MainWindow", "Terima kasih telah melakukan pemesanan"))
        self.label_penutup.setText(_translate("MainWindow", "Selamat menonton dan semoga Anda menikmati filmnya!."))
        self.tombol_kembali.setText(_translate("MainWindow", "KEMBALI"))
        self.label_ticketing.setText(_translate("MainWindow", "TICKETING"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
