# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding:0 ;\n"
"    margin:0 ;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: ;\n"
"    background-image: url(:/images/1a800x6001.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(750, 50))
        self.navbar.setMaximumSize(QtCore.QSize(800, 50))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #1e1e2f;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  rgb(220, 165, 50);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.HLayout_3 = QtWidgets.QHBoxLayout()
        self.HLayout_3.setObjectName("HLayout_3")
        self.tombol_kembali = QtWidgets.QPushButton(self.navbar)
        self.tombol_kembali.setMinimumSize(QtCore.QSize(50, 50))
        self.tombol_kembali.setObjectName("tombol_kembali")
        self.HLayout_3.addWidget(self.tombol_kembali)
        self.icon_vline = QtWidgets.QLabel(self.navbar)
        self.icon_vline.setMinimumSize(QtCore.QSize(20, 35))
        self.icon_vline.setMaximumSize(QtCore.QSize(20, 35))
        self.icon_vline.setText("")
        self.icon_vline.setPixmap(QtGui.QPixmap(":/icons/icons8-line-100.png"))
        self.icon_vline.setScaledContents(True)
        self.icon_vline.setObjectName("icon_vline")
        self.HLayout_3.addWidget(self.icon_vline)
        self.label_home = QtWidgets.QPushButton(self.navbar)
        self.label_home.setMinimumSize(QtCore.QSize(50, 50))
        self.label_home.setObjectName("label_home")
        self.HLayout_3.addWidget(self.label_home)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_3.addItem(spacerItem)
        self.label_admin = QtWidgets.QPushButton(self.navbar)
        self.label_admin.setMinimumSize(QtCore.QSize(50, 50))
        self.label_admin.setObjectName("label_admin")
        self.HLayout_3.addWidget(self.label_admin)
        self.horizontalLayout_4.addLayout(self.HLayout_3)
        self.verticalLayout.addWidget(self.navbar)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setStyleSheet("")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.frame_2 = QtWidgets.QFrame(self.frame_1)
        self.frame_2.setGeometry(QtCore.QRect(89, 79, 611, 371))
        self.frame_2.setStyleSheet("\n"
"QLabel {\n"
"    font: 63 10pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 10px;\n"
"    padding: 4px 10px;\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgb(230, 140, 45); /* Efek tambahan agar terlihat jelas */\n"
"    color: white;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(39, 69, 531, 191))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.to_pesanfilm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.to_pesanfilm.setMinimumSize(QtCore.QSize(100, 150))
        self.to_pesanfilm.setStyleSheet("")
        self.to_pesanfilm.setObjectName("to_pesanfilm")
        self.horizontalLayout.addWidget(self.to_pesanfilm)
        self.to_updatefilm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.to_updatefilm.setMinimumSize(QtCore.QSize(100, 150))
        self.to_updatefilm.setStyleSheet("")
        self.to_updatefilm.setObjectName("to_updatefilm")
        self.horizontalLayout.addWidget(self.to_updatefilm)
        self.to_laporan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.to_laporan.setMinimumSize(QtCore.QSize(100, 150))
        self.to_laporan.setStyleSheet("")
        self.to_laporan.setObjectName("to_laporan")
        self.horizontalLayout.addWidget(self.to_laporan)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(39, 240, 531, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_pesanfilm = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_pesanfilm.setObjectName("label_pesanfilm")
        self.horizontalLayout_2.addWidget(self.label_pesanfilm, 0, QtCore.Qt.AlignHCenter)
        self.label_update = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_update.setObjectName("label_update")
        self.horizontalLayout_2.addWidget(self.label_update, 0, QtCore.Qt.AlignHCenter)
        self.label_laporan = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_laporan.setObjectName("label_laporan")
        self.horizontalLayout_2.addWidget(self.label_laporan, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Absolute Cinema"))
        self.tombol_kembali.setText(_translate("MainWindow", "LOG OUT"))
        self.label_home.setText(_translate("MainWindow", "HOME"))
        self.label_admin.setText(_translate("MainWindow", "ADMIN"))
        self.to_pesanfilm.setText(_translate("MainWindow", "PESAN FILM"))
        self.to_updatefilm.setText(_translate("MainWindow", "UPDATE"))
        self.to_laporan.setText(_translate("MainWindow", "LAPORAN"))
        self.label_pesanfilm.setText(_translate("MainWindow", "PESAN FILM"))
        self.label_update.setText(_translate("MainWindow", "UPDATE"))
        self.label_laporan.setText(_translate("MainWindow", "LAPORAN"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
