# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding:0 ;\n"
"    margin:0 ;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: ;\n"
"    background-image: url(:/images/1a800x6001.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(750, 50))
        self.navbar.setMaximumSize(QtCore.QSize(800, 50))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #1e1e2f;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  rgb(220, 165, 50);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Hlayout_1 = QtWidgets.QHBoxLayout()
        self.Hlayout_1.setObjectName("Hlayout_1")
        self.label_home = QtWidgets.QPushButton(self.navbar)
        self.label_home.setMinimumSize(QtCore.QSize(50, 50))
        self.label_home.setObjectName("label_home")
        self.Hlayout_1.addWidget(self.label_home)
        self.arrow1 = QtWidgets.QLabel(self.navbar)
        self.arrow1.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow1.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow1.setText("")
        self.arrow1.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow1.setScaledContents(True)
        self.arrow1.setObjectName("arrow1")
        self.Hlayout_1.addWidget(self.arrow1)
        self.label_detail = QtWidgets.QPushButton(self.navbar)
        self.label_detail.setMinimumSize(QtCore.QSize(50, 50))
        self.label_detail.setObjectName("label_detail")
        self.Hlayout_1.addWidget(self.label_detail)
        self.arrow2 = QtWidgets.QLabel(self.navbar)
        self.arrow2.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow2.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow2.setText("")
        self.arrow2.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow2.setScaledContents(True)
        self.arrow2.setObjectName("arrow2")
        self.Hlayout_1.addWidget(self.arrow2)
        self.label_seats = QtWidgets.QPushButton(self.navbar)
        self.label_seats.setMinimumSize(QtCore.QSize(50, 50))
        self.label_seats.setObjectName("label_seats")
        self.Hlayout_1.addWidget(self.label_seats)
        self.arrow3 = QtWidgets.QLabel(self.navbar)
        self.arrow3.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow3.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow3.setText("")
        self.arrow3.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow3.setScaledContents(True)
        self.arrow3.setObjectName("arrow3")
        self.Hlayout_1.addWidget(self.arrow3)
        self.label_payment = QtWidgets.QPushButton(self.navbar)
        self.label_payment.setMinimumSize(QtCore.QSize(50, 50))
        self.label_payment.setObjectName("label_payment")
        self.Hlayout_1.addWidget(self.label_payment)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.Hlayout_1.addItem(spacerItem)
        self.user_name = QtWidgets.QPushButton(self.navbar)
        self.user_name.setMinimumSize(QtCore.QSize(50, 50))
        self.user_name.setObjectName("user_name")
        self.Hlayout_1.addWidget(self.user_name)
        self.horizontalLayout_4.addLayout(self.Hlayout_1)
        self.verticalLayout.addWidget(self.navbar)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setStyleSheet("#frame {\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"    font: 63 9pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.frame_2 = QtWidgets.QFrame(self.frame_1)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 501, 31))
        self.frame_2.setStyleSheet("\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"background-color: rgb(29, 26, 27);\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_paymentinformation = QtWidgets.QLabel(self.frame_2)
        self.label_paymentinformation.setObjectName("label_paymentinformation")
        self.horizontalLayout.addWidget(self.label_paymentinformation, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.frame_1)
        self.frame_3.setGeometry(QtCore.QRect(520, 70, 231, 91))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"color: rgb(0, 0, 0);\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13pt;\n"
"    font-weight: bold;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.isi_harga = QtWidgets.QLabel(self.frame_3)
        self.isi_harga.setObjectName("isi_harga")
        self.verticalLayout_3.addWidget(self.isi_harga)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 449, 501, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VLayout_1.setContentsMargins(0, 0, 0, 0)
        self.VLayout_1.setObjectName("VLayout_1")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setStyleSheet("    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.checkBox.setObjectName("checkBox")
        self.VLayout_1.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setStyleSheet("    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.checkBox_2.setObjectName("checkBox_2")
        self.VLayout_1.addWidget(self.checkBox_2)
        self.bg_hijau1 = QtWidgets.QLabel(self.frame_1)
        self.bg_hijau1.setGeometry(QtCore.QRect(520, 40, 231, 31))
        self.bg_hijau1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"")
        self.bg_hijau1.setText("")
        self.bg_hijau1.setObjectName("bg_hijau1")
        self.frame_4 = QtWidgets.QFrame(self.frame_1)
        self.frame_4.setGeometry(QtCore.QRect(520, 210, 231, 91))
        self.frame_4.setStyleSheet("    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13pt;\n"
"    font-weight: bold;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.isi_fee = QtWidgets.QLabel(self.frame_4)
        self.isi_fee.setObjectName("isi_fee")
        self.verticalLayout_4.addWidget(self.isi_fee)
        self.bg_hijau2 = QtWidgets.QLabel(self.frame_1)
        self.bg_hijau2.setGeometry(QtCore.QRect(520, 180, 231, 31))
        self.bg_hijau2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));")
        self.bg_hijau2.setText("")
        self.bg_hijau2.setObjectName("bg_hijau2")
        self.frame_5 = QtWidgets.QFrame(self.frame_1)
        self.frame_5.setGeometry(QtCore.QRect(520, 350, 231, 91))
        self.frame_5.setStyleSheet("    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 13pt;\n"
"    font-weight: bold;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.isi_totalharga = QtWidgets.QLabel(self.frame_5)
        self.isi_totalharga.setObjectName("isi_totalharga")
        self.verticalLayout_5.addWidget(self.isi_totalharga)
        self.bg_hijau3 = QtWidgets.QLabel(self.frame_1)
        self.bg_hijau3.setGeometry(QtCore.QRect(520, 320, 231, 31))
        self.bg_hijau3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));")
        self.bg_hijau3.setText("")
        self.bg_hijau3.setObjectName("bg_hijau3")
        self.label_harga = QtWidgets.QLabel(self.frame_1)
        self.label_harga.setGeometry(QtCore.QRect(530, 45, 131, 21))
        self.label_harga.setStyleSheet("color: rgb(63, 63, 63);\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.label_harga.setObjectName("label_harga")
        self.label_fee = QtWidgets.QLabel(self.frame_1)
        self.label_fee.setGeometry(QtCore.QRect(530, 180, 131, 31))
        self.label_fee.setStyleSheet("color: rgb(63, 63, 63);\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.label_fee.setObjectName("label_fee")
        self.label_totalharga = QtWidgets.QLabel(self.frame_1)
        self.label_totalharga.setGeometry(QtCore.QRect(530, 320, 131, 31))
        self.label_totalharga.setStyleSheet("color: rgb(63, 63, 63);\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.label_totalharga.setObjectName("label_totalharga")
        self.frame_6 = QtWidgets.QFrame(self.frame_1)
        self.frame_6.setGeometry(QtCore.QRect(9, 69, 481, 351))
        self.frame_6.setStyleSheet("#frame_6 {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"#frame_8 {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"#frame_7 {\n"
"    background-color: rgb(185, 185, 185);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(39, 29, 401, 131))
        self.frame_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_8)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(9, 9, 121, 71))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.VLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.VLayout_2.setContentsMargins(0, 0, 0, 0)
        self.VLayout_2.setObjectName("VLayout_2")
        self.label_namafilm = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_namafilm.setObjectName("label_namafilm")
        self.VLayout_2.addWidget(self.label_namafilm)
        self.label_kursi = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_kursi.setObjectName("label_kursi")
        self.VLayout_2.addWidget(self.label_kursi)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_8)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(129, 10, 261, 71))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.VLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.VLayout_3.setContentsMargins(0, 0, 0, 0)
        self.VLayout_3.setObjectName("VLayout_3")
        self.isi_namafilm = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.isi_namafilm.setObjectName("isi_namafilm")
        self.VLayout_3.addWidget(self.isi_namafilm)
        self.isi_kursidipilih = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.isi_kursidipilih.setObjectName("isi_kursidipilih")
        self.VLayout_3.addWidget(self.isi_kursidipilih)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(40, 190, 401, 131))
        self.frame_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_7)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 9, 122, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.VLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.VLayout_5.setContentsMargins(0, 0, 0, 0)
        self.VLayout_5.setObjectName("VLayout_5")
        self.label_bank = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_bank.setObjectName("label_bank")
        self.VLayout_5.addWidget(self.label_bank)
        self.label_namauser = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_namauser.setObjectName("label_namauser")
        self.VLayout_5.addWidget(self.label_namauser)
        self.label_noVA = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_noVA.setObjectName("label_noVA")
        self.VLayout_5.addWidget(self.label_noVA)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_7)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(130, 9, 252, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.VLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.VLayout_4.setContentsMargins(0, 0, 0, 0)
        self.VLayout_4.setObjectName("VLayout_4")
        self.comboBox_payment = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.comboBox_payment.setMinimumSize(QtCore.QSize(250, 30))
        self.comboBox_payment.setMaximumSize(QtCore.QSize(250, 30))
        self.comboBox_payment.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"border: 1px solid;")
        self.comboBox_payment.setObjectName("comboBox_payment")
        self.comboBox_payment.addItem("")
        self.comboBox_payment.addItem("")
        self.comboBox_payment.addItem("")
        self.comboBox_payment.addItem("")
        self.VLayout_4.addWidget(self.comboBox_payment)
        self.isi_namauser = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.isi_namauser.setObjectName("isi_namauser")
        self.VLayout_4.addWidget(self.isi_namauser)
        self.isi_VA = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.isi_VA.setObjectName("isi_VA")
        self.VLayout_4.addWidget(self.isi_VA)
        self.frame_7.raise_()
        self.frame_8.raise_()
        self.tombol_lanjut = QtWidgets.QPushButton(self.frame_1)
        self.tombol_lanjut.setGeometry(QtCore.QRect(640, 460, 80, 30))
        self.tombol_lanjut.setMinimumSize(QtCore.QSize(80, 30))
        self.tombol_lanjut.setMaximumSize(QtCore.QSize(80, 30))
        self.tombol_lanjut.setStyleSheet("\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.tombol_lanjut.setObjectName("tombol_lanjut")
        self.tombol_kembali = QtWidgets.QPushButton(self.frame_1)
        self.tombol_kembali.setGeometry(QtCore.QRect(550, 460, 80, 30))
        self.tombol_kembali.setMinimumSize(QtCore.QSize(80, 30))
        self.tombol_kembali.setMaximumSize(QtCore.QSize(80, 30))
        self.tombol_kembali.setStyleSheet("\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;")
        self.tombol_kembali.setObjectName("tombol_kembali")
        self.verticalLayout.addWidget(self.frame_1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Absolute Cinema"))
        self.label_home.setText(_translate("MainWindow", "HOME"))
        self.label_detail.setText(_translate("MainWindow", "DETAIL"))
        self.label_seats.setText(_translate("MainWindow", "SEATS"))
        self.label_payment.setText(_translate("MainWindow", "PAYMENT"))
        self.user_name.setText(_translate("MainWindow", "USER_NAME"))
        self.label_paymentinformation.setText(_translate("MainWindow", "PAYMENT INFORMATION"))
        self.isi_harga.setText(_translate("MainWindow", "( perhitungan harga )"))
        self.checkBox.setText(_translate("MainWindow", "I understand that child under 3 are not allowed inside cinema."))
        self.checkBox_2.setText(_translate("MainWindow", "I agree with all the rules in the cinema."))
        self.isi_fee.setText(_translate("MainWindow", "( pajak pembayaran )"))
        self.isi_totalharga.setText(_translate("MainWindow", "( hitung seluruh total )"))
        self.label_harga.setText(_translate("MainWindow", "HARGA :"))
        self.label_fee.setText(_translate("MainWindow", "FEE :"))
        self.label_totalharga.setText(_translate("MainWindow", "TOTAL HARGA :"))
        self.label_namafilm.setText(_translate("MainWindow", "Nama Film                 :"))
        self.label_kursi.setText(_translate("MainWindow", "Kursi yang dipilih     :"))
        self.isi_namafilm.setText(_translate("MainWindow", "db_namafilm"))
        self.isi_kursidipilih.setText(_translate("MainWindow", "db_kursi"))
        self.label_bank.setText(_translate("MainWindow", "Bank yang dipilih     :"))
        self.label_namauser.setText(_translate("MainWindow", "Nama                         :"))
        self.label_noVA.setText(_translate("MainWindow", "No VA                        :"))
        self.comboBox_payment.setItemText(0, _translate("MainWindow", "   BCA"))
        self.comboBox_payment.setItemText(1, _translate("MainWindow", "   Mandiri"))
        self.comboBox_payment.setItemText(2, _translate("MainWindow", "   BRI"))
        self.comboBox_payment.setItemText(3, _translate("MainWindow", "   DANA"))
        self.isi_namauser.setText(_translate("MainWindow", "db_namauser"))
        self.isi_VA.setText(_translate("MainWindow", "( create VA Bank )"))
        self.tombol_lanjut.setText(_translate("MainWindow", "LANJUT"))
        self.tombol_kembali.setText(_translate("MainWindow", "KEMBALI"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
