# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pilih_film.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding:0 ;\n"
"    margin:0 ;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: ;\n"
"    background-image: url(:/images/1a800x6001.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(750, 50))
        self.navbar.setMaximumSize(QtCore.QSize(800, 50))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #1e1e2f;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  rgb(220, 165, 50);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"#label_user:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.HLayout_3 = QtWidgets.QHBoxLayout()
        self.HLayout_3.setObjectName("HLayout_3")
        self.label_home = QtWidgets.QPushButton(self.navbar)
        self.label_home.setMinimumSize(QtCore.QSize(50, 50))
        self.label_home.setObjectName("label_home")
        self.HLayout_3.addWidget(self.label_home)
        self.arrow1 = QtWidgets.QLabel(self.navbar)
        self.arrow1.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow1.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow1.setText("")
        self.arrow1.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow1.setScaledContents(True)
        self.arrow1.setObjectName("arrow1")
        self.HLayout_3.addWidget(self.arrow1)
        self.label_detail = QtWidgets.QPushButton(self.navbar)
        self.label_detail.setMinimumSize(QtCore.QSize(50, 50))
        self.label_detail.setObjectName("label_detail")
        self.HLayout_3.addWidget(self.label_detail)
        self.arrow2 = QtWidgets.QLabel(self.navbar)
        self.arrow2.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow2.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow2.setText("")
        self.arrow2.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow2.setScaledContents(True)
        self.arrow2.setObjectName("arrow2")
        self.HLayout_3.addWidget(self.arrow2)
        self.label_seats = QtWidgets.QPushButton(self.navbar)
        self.label_seats.setMinimumSize(QtCore.QSize(50, 50))
        self.label_seats.setObjectName("label_seats")
        self.HLayout_3.addWidget(self.label_seats)
        self.arrow3 = QtWidgets.QLabel(self.navbar)
        self.arrow3.setMinimumSize(QtCore.QSize(20, 20))
        self.arrow3.setMaximumSize(QtCore.QSize(20, 20))
        self.arrow3.setText("")
        self.arrow3.setPixmap(QtGui.QPixmap(":/icons/icons8-triangle-arrow-48.png"))
        self.arrow3.setScaledContents(True)
        self.arrow3.setObjectName("arrow3")
        self.HLayout_3.addWidget(self.arrow3)
        self.label_payment = QtWidgets.QPushButton(self.navbar)
        self.label_payment.setMinimumSize(QtCore.QSize(50, 50))
        self.label_payment.setObjectName("label_payment")
        self.HLayout_3.addWidget(self.label_payment)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_3.addItem(spacerItem)
        self.label_user = QtWidgets.QPushButton(self.navbar)
        self.label_user.setMinimumSize(QtCore.QSize(50, 50))
        self.label_user.setObjectName("label_user")
        self.HLayout_3.addWidget(self.label_user)
        self.horizontalLayout_4.addLayout(self.HLayout_3)
        self.verticalLayout.addWidget(self.navbar)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLabel{  \n"
"      font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 480, 771, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.HLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.HLayout_6.setContentsMargins(0, 0, 0, 0)
        self.HLayout_6.setObjectName("HLayout_6")
        self.isi_judul6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.isi_judul6.setObjectName("isi_judul6")
        self.HLayout_6.addWidget(self.isi_judul6, 0, QtCore.Qt.AlignHCenter)
        self.isi_judul7 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.isi_judul7.setObjectName("isi_judul7")
        self.HLayout_6.addWidget(self.isi_judul7, 0, QtCore.Qt.AlignHCenter)
        self.isi_judul8 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.isi_judul8.setObjectName("isi_judul8")
        self.HLayout_6.addWidget(self.isi_judul8, 0, QtCore.Qt.AlignHCenter)
        self.isi_judul9 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.isi_judul9.setObjectName("isi_judul9")
        self.HLayout_6.addWidget(self.isi_judul9, 0, QtCore.Qt.AlignHCenter)
        self.isi_judul10 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.isi_judul10.setObjectName("isi_judul10")
        self.HLayout_6.addWidget(self.isi_judul10, 0, QtCore.Qt.AlignHCenter)
        self.label_comingsoon = QtWidgets.QLabel(self.frame)
        self.label_comingsoon.setGeometry(QtCore.QRect(26, 282, 191, 31))
        self.label_comingsoon.setObjectName("label_comingsoon")
        self.label_nowplaying = QtWidgets.QLabel(self.frame)
        self.label_nowplaying.setGeometry(QtCore.QRect(30, 10, 181, 31))
        self.label_nowplaying.setObjectName("label_nowplaying")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(-1, 29, 781, 201))
        self.frame_2.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 35px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-clip: border;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 776, 191))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.HLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.HLayout_2.setContentsMargins(0, 0, 0, 0)
        self.HLayout_2.setObjectName("HLayout_2")
        self.isi_poster1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster1.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster1.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster1.setObjectName("isi_poster1")
        self.HLayout_2.addWidget(self.isi_poster1)
        self.isi_poster2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster2.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster2.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster2.setObjectName("isi_poster2")
        self.HLayout_2.addWidget(self.isi_poster2)
        self.isi_poster3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster3.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster3.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster3.setObjectName("isi_poster3")
        self.HLayout_2.addWidget(self.isi_poster3)
        self.isi_poster4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster4.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster4.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster4.setObjectName("isi_poster4")
        self.HLayout_2.addWidget(self.isi_poster4)
        self.isi_poster5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster5.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster5.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster5.setObjectName("isi_poster5")
        self.HLayout_2.addWidget(self.isi_poster5)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(-1, 309, 781, 191))
        self.frame_3.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 35px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-clip: border;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, -21, 776, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HLayout_1.setContentsMargins(0, 0, 0, 0)
        self.HLayout_1.setObjectName("HLayout_1")
        self.isi_poster6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster6.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster6.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster6.setObjectName("isi_poster6")
        self.HLayout_1.addWidget(self.isi_poster6)
        self.isi_poster7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster7.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster7.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster7.setObjectName("isi_poster7")
        self.HLayout_1.addWidget(self.isi_poster7)
        self.isi_poster8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster8.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster8.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster8.setObjectName("isi_poster8")
        self.HLayout_1.addWidget(self.isi_poster8)
        self.isi_poster9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster9.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster9.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster9.setObjectName("isi_poster9")
        self.HLayout_1.addWidget(self.isi_poster9)
        self.isi_poster10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster10.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster10.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster10.setObjectName("isi_poster10")
        self.HLayout_1.addWidget(self.isi_poster10)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(-1, 210, 791, 61))
        self.frame_4.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"    font: 63 9pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.HLayout_5 = QtWidgets.QHBoxLayout()
        self.HLayout_5.setObjectName("HLayout_5")
        self.isi_judul1 = QtWidgets.QPushButton(self.frame_4)
        self.isi_judul1.setObjectName("isi_judul1")
        self.HLayout_5.addWidget(self.isi_judul1)
        self.isi_judul2 = QtWidgets.QPushButton(self.frame_4)
        self.isi_judul2.setObjectName("isi_judul2")
        self.HLayout_5.addWidget(self.isi_judul2)
        self.isi_judul3 = QtWidgets.QPushButton(self.frame_4)
        self.isi_judul3.setObjectName("isi_judul3")
        self.HLayout_5.addWidget(self.isi_judul3)
        self.isi_judul4 = QtWidgets.QPushButton(self.frame_4)
        self.isi_judul4.setObjectName("isi_judul4")
        self.HLayout_5.addWidget(self.isi_judul4)
        self.isi_judul5 = QtWidgets.QPushButton(self.frame_4)
        self.isi_judul5.setObjectName("isi_judul5")
        self.HLayout_5.addWidget(self.isi_judul5)
        self.horizontalLayout_7.addLayout(self.HLayout_5)
        self.bg_hijau1 = QtWidgets.QLabel(self.frame)
        self.bg_hijau1.setGeometry(QtCore.QRect(0, 10, 221, 31))
        self.bg_hijau1.setStyleSheet("background-color: rgb(0, 165, 132);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"")
        self.bg_hijau1.setText("")
        self.bg_hijau1.setObjectName("bg_hijau1")
        self.bg_hijau2 = QtWidgets.QLabel(self.frame)
        self.bg_hijau2.setGeometry(QtCore.QRect(0, 280, 221, 31))
        self.bg_hijau2.setStyleSheet("background-color: rgb(0, 165, 132);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"")
        self.bg_hijau2.setText("")
        self.bg_hijau2.setObjectName("bg_hijau2")
        self.bg_hijau2.raise_()
        self.bg_hijau1.raise_()
        self.label_nowplaying.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.label_comingsoon.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Absolute Cinema"))
        self.label_home.setText(_translate("MainWindow", "HOME"))
        self.label_detail.setText(_translate("MainWindow", "DETAIL"))
        self.label_seats.setText(_translate("MainWindow", "SEATS"))
        self.label_payment.setText(_translate("MainWindow", "PAYMENT"))
        self.label_user.setText(_translate("MainWindow", "USER_NAME"))
        self.isi_judul6.setText(_translate("MainWindow", "Judul_6"))
        self.isi_judul7.setText(_translate("MainWindow", "Judul_7"))
        self.isi_judul8.setText(_translate("MainWindow", "Judul_8"))
        self.isi_judul9.setText(_translate("MainWindow", "Judul_9"))
        self.isi_judul10.setText(_translate("MainWindow", "Judul_10"))
        self.label_comingsoon.setText(_translate("MainWindow", "COMING SOON"))
        self.label_nowplaying.setText(_translate("MainWindow", "NOW PLAYING"))
        self.isi_poster1.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster2.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster3.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster4.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster5.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster6.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster7.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster8.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster9.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster10.setText(_translate("MainWindow", "TextLabel"))
        self.isi_judul1.setText(_translate("MainWindow", "Judul_1"))
        self.isi_judul2.setText(_translate("MainWindow", "Judul_2"))
        self.isi_judul3.setText(_translate("MainWindow", "Judul_3"))
        self.isi_judul4.setText(_translate("MainWindow", "Judul_4"))
        self.isi_judul5.setText(_translate("MainWindow", "Judul_5"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
