# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QToolButton
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding:0 ;\n"
"    margin:0 ;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: ;\n"
"    background-image: url(:/images/1a800x600_11.png);\n"
"}\n"
"#halamanRegister {\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Putih semi-transparan */\n"
"    border-radius: 20px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.3);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(9,10,37);\n"
"    padding: 5px 3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"    font: 63 9pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#to_register:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgb(230, 140, 45); /* Efek tambahan agar terlihat jelas */\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"#to_login{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"#to_login:hover{\n"
"    color: rgb(223, 190, 56);\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.halamanRegister = QtWidgets.QWidget(self.centralwidget)
        self.halamanRegister.setGeometry(QtCore.QRect(460, 80, 300, 450))
        self.halamanRegister.setMinimumSize(QtCore.QSize(300, 450))
        self.halamanRegister.setMaximumSize(QtCore.QSize(300, 450))
        self.halamanRegister.setObjectName("halamanRegister")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.halamanRegister)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.halamanRegister)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.icon_register = QtWidgets.QLabel(self.frame)
        self.icon_register.setMinimumSize(QtCore.QSize(50, 50))
        self.icon_register.setMaximumSize(QtCore.QSize(50, 50))
        self.icon_register.setText("")
        self.icon_register.setPixmap(QtGui.QPixmap(":/icons/userw.png"))
        self.icon_register.setScaledContents(True)
        self.icon_register.setObjectName("icon_register")
        self.verticalLayout_3.addWidget(self.icon_register, 0, QtCore.Qt.AlignHCenter)
        self.label_register = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_register.setFont(font)
        self.label_register.setObjectName("label_register")
        self.verticalLayout_3.addWidget(self.label_register, 0, QtCore.Qt.AlignHCenter)
        self.label_deskripsi = QtWidgets.QLabel(self.frame)
        self.label_deskripsi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_deskripsi.setObjectName("label_deskripsi")
        self.verticalLayout_3.addWidget(self.label_deskripsi)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_info = QtWidgets.QLabel(self.frame)
        self.label_info.setText("")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.verticalLayout_3.addWidget(self.label_info)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.isi_username = QtWidgets.QLineEdit(self.frame_2)
        self.isi_username.setText("")
        self.isi_username.setObjectName("isi_username")
        self.verticalLayout_4.addWidget(self.isi_username)
        self.isi_password = QtWidgets.QLineEdit(self.frame_2)
        self.isi_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.isi_password.setObjectName("isi_password")
        self.verticalLayout_4.addWidget(self.isi_password)
        self.isi_confirmpw = QtWidgets.QLineEdit(self.frame_2)
        self.isi_confirmpw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.isi_confirmpw.setObjectName("isi_confirmpw")
        self.verticalLayout_4.addWidget(self.isi_confirmpw)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.syarat_1 = QtWidgets.QCheckBox(self.frame)
        self.syarat_1.setObjectName("syarat_1")
        self.verticalLayout_3.addWidget(self.syarat_1)
        self.to_register = QtWidgets.QPushButton(self.frame)
        self.to_register.setMinimumSize(QtCore.QSize(0, 40))
        self.to_register.setMaximumSize(QtCore.QSize(16777215, 40))
        self.to_register.setObjectName("to_register")
        self.verticalLayout_3.addWidget(self.to_register)
        self.to_login = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(7)
        self.to_login.setFont(font)
        self.to_login.setObjectName("to_login")
        self.verticalLayout_3.addWidget(self.to_login, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self._add_eye_toggle(self.isi_confirmpw)
        self._add_eye_toggle(self.isi_password)

    def _add_eye_toggle(self, line_edit):
        toggle_btn = QToolButton(line_edit)
        toggle_btn.setIcon(QIcon(""))   
        toggle_btn.setCheckable(True)
        toggle_btn.setCursor(Qt.PointingHandCursor)
        toggle_btn.setStyleSheet("QToolButton { border: none; background: transparent; }")

        def update_position():
            rect = line_edit.rect()
            toggle_btn.move(rect.right() - 24, (rect.height() - toggle_btn.height()) // 2)

        def toggle():
            if toggle_btn.isChecked():
                line_edit.setEchoMode(line_edit.Normal)
                toggle_btn.setIcon(QIcon(":/icons/eyes-close.png"))
            else:
                line_edit.setEchoMode(line_edit.Password)
                toggle_btn.setIcon(QIcon(":/icons/eyes.png"))

        toggle_btn.clicked.connect(toggle)
        line_edit.textChanged.connect(update_position)
        line_edit.resizeEvent = lambda event: (update_position(), None)[1]
        update_position()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Absolute Cinema"))
        self.label_register.setText(_translate("MainWindow", "Sign Up"))
        self.label_deskripsi.setText(_translate("MainWindow", "Enter your information below"))
        self.isi_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.isi_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.isi_confirmpw.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.syarat_1.setText(_translate("MainWindow", "Agree with our terms"))
        self.to_register.setText(_translate("MainWindow", "Register"))
        self.to_login.setText(_translate("MainWindow", "Already registered? Login"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
