# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Update_detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding:0 ;\n"
"    margin:0 ;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: ;\n"
"    background-image: url(:/images/1a800x6001.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(750, 50))
        self.navbar.setMaximumSize(QtCore.QSize(800, 50))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #1e1e2f;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  rgb(220, 165, 50);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.HLayout_3 = QtWidgets.QHBoxLayout()
        self.HLayout_3.setObjectName("HLayout_3")
        self.tombol_kembali = QtWidgets.QPushButton(self.navbar)
        self.tombol_kembali.setMinimumSize(QtCore.QSize(50, 50))
        self.tombol_kembali.setObjectName("tombol_kembali")
        self.HLayout_3.addWidget(self.tombol_kembali)
        self.icon_vline = QtWidgets.QLabel(self.navbar)
        self.icon_vline.setMinimumSize(QtCore.QSize(20, 35))
        self.icon_vline.setMaximumSize(QtCore.QSize(20, 35))
        self.icon_vline.setText("")
        self.icon_vline.setPixmap(QtGui.QPixmap(":/icons/icons8-line-100.png"))
        self.icon_vline.setScaledContents(True)
        self.icon_vline.setObjectName("icon_vline")
        self.HLayout_3.addWidget(self.icon_vline)
        self.tombol_save = QtWidgets.QPushButton(self.navbar)
        self.tombol_save.setMinimumSize(QtCore.QSize(50, 50))
        self.tombol_save.setObjectName("tombol_save")
        self.HLayout_3.addWidget(self.tombol_save)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_3.addItem(spacerItem)
        self.label_admin = QtWidgets.QPushButton(self.navbar)
        self.label_admin.setMinimumSize(QtCore.QSize(50, 50))
        self.label_admin.setObjectName("label_admin")
        self.HLayout_3.addWidget(self.label_admin)
        self.horizontalLayout_4.addLayout(self.HLayout_3)
        self.verticalLayout.addWidget(self.navbar)
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setStyleSheet("QLabel{  \n"
"      font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {  \n"
"      font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 2px;\n"
"    padding-top: 3px;\n"
"    background-color: rgb(230, 140, 45); /* Efek tambahan agar terlihat jelas */\n"
"    color: white;\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.isi_posterfilm = QtWidgets.QLabel(self.frame_1)
        self.isi_posterfilm.setGeometry(QtCore.QRect(10, 10, 151, 191))
        self.isi_posterfilm.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 35px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-clip: border;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.isi_posterfilm.setText("")
        self.isi_posterfilm.setObjectName("isi_posterfilm")
        self.frame_2 = QtWidgets.QFrame(self.frame_1)
        self.frame_2.setGeometry(QtCore.QRect(179, 9, 601, 281))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"border: 1px solid black;\n"
"background-color: rgb(30, 30, 47);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.1); /* semi transparan */\n"
"    border: 1px solid rgba(255, 255, 255, 0.3);\n"
"    border-radius: 8px;\n"
"    padding: 6px 10px;\n"
"    color: black;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(223, 190, 56); /* warna fokus */\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    \n"
"    background-color: rgb(168, 168, 168);\n"
"    border: 1px solid rgba(255, 255, 255, 0.3);\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    color: black;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(255, 200, 100); /* garis saat fokus */\n"
"    background-color: rgba(255, 255, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 39, 91, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.VLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.VLayout_3.setContentsMargins(0, 0, 0, 0)
        self.VLayout_3.setObjectName("VLayout_3")
        self.label_produksi = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_produksi.setObjectName("label_produksi")
        self.VLayout_3.addWidget(self.label_produksi)
        self.label_sutradara = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_sutradara.setObjectName("label_sutradara")
        self.VLayout_3.addWidget(self.label_sutradara)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(100, 40, 182, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.VLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.VLayout_4.setContentsMargins(0, 0, 0, 0)
        self.VLayout_4.setObjectName("VLayout_4")
        self.edit_produksi = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edit_produksi.setMinimumSize(QtCore.QSize(165, 32))
        self.edit_produksi.setMaximumSize(QtCore.QSize(165, 32))
        self.edit_produksi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_produksi.setObjectName("edit_produksi")
        self.VLayout_4.addWidget(self.edit_produksi)
        self.edit_sutradara = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edit_sutradara.setMinimumSize(QtCore.QSize(165, 32))
        self.edit_sutradara.setMaximumSize(QtCore.QSize(165, 32))
        self.edit_sutradara.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_sutradara.setObjectName("edit_sutradara")
        self.VLayout_4.addWidget(self.edit_sutradara)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(-1, 0, 601, 41))
        self.frame_4.setStyleSheet("#frame_4 {\n"
"    background-color: rgb(0, 165, 132);\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.isi_judulfilm = QtWidgets.QLabel(self.frame_4)
        self.isi_judulfilm.setGeometry(QtCore.QRect(0, 5, 601, 31))
        self.isi_judulfilm.setStyleSheet("font-size: 14px;")
        self.isi_judulfilm.setAlignment(QtCore.Qt.AlignCenter)
        self.isi_judulfilm.setObjectName("isi_judulfilm")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(-1, 129, 601, 151))
        self.frame_5.setStyleSheet("#frame_5 {\n"
"background-color: white;\n"
" border-bottom-right-radius: 20px;\n"
" border-bottom-left-radius: 20px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_sinopsis = QtWidgets.QLabel(self.frame_5)
        self.label_sinopsis.setGeometry(QtCore.QRect(10, 0, 71, 31))
        self.label_sinopsis.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_sinopsis.setObjectName("label_sinopsis")
        self.edit_sinopsis = QtWidgets.QTextEdit(self.frame_5)
        self.edit_sinopsis.setGeometry(QtCore.QRect(13, 30, 571, 101))
        self.edit_sinopsis.setObjectName("edit_sinopsis")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(280, 40, 111, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.VLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.VLayout_5.setContentsMargins(0, 0, 0, 0)
        self.VLayout_5.setObjectName("VLayout_5")
        self.label_aktor = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_aktor.setObjectName("label_aktor")
        self.VLayout_5.addWidget(self.label_aktor)
        self.label_age = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_age.setObjectName("label_age")
        self.VLayout_5.addWidget(self.label_age)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(390, 40, 211, 91))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.VLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.VLayout_6.setContentsMargins(0, 0, 0, 0)
        self.VLayout_6.setObjectName("VLayout_6")
        self.edit_aktor = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.edit_aktor.setMinimumSize(QtCore.QSize(165, 32))
        self.edit_aktor.setMaximumSize(QtCore.QSize(165, 32))
        self.edit_aktor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_aktor.setObjectName("edit_aktor")
        self.VLayout_6.addWidget(self.edit_aktor)
        self.edit_age = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.edit_age.setMinimumSize(QtCore.QSize(165, 32))
        self.edit_age.setMaximumSize(QtCore.QSize(165, 32))
        self.edit_age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edit_age.setObjectName("edit_age")
        self.VLayout_6.addWidget(self.edit_age)
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.frame_4.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.verticalLayoutWidget_5.raise_()
        self.frame_5.raise_()
        self.frame_3 = QtWidgets.QFrame(self.frame_1)
        self.frame_3.setGeometry(QtCore.QRect(-1, 299, 781, 231))
        self.frame_3.setStyleSheet("#frame_3 {\n"
"border: 1px solid black;\n"
"background-color: rgb(30, 30, 47);\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"    font: 63 11pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgb(230, 140, 45); /* Efek tambahan agar terlihat jelas */\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 581, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.HLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.HLayout_5.setContentsMargins(0, 0, 0, 0)
        self.HLayout_5.setSpacing(3)
        self.HLayout_5.setObjectName("HLayout_5")
        self.tanggal_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.tanggal_1.setMinimumSize(QtCore.QSize(100, 50))
        self.tanggal_1.setMaximumSize(QtCore.QSize(100, 50))
        self.tanggal_1.setObjectName("tanggal_1")
        self.HLayout_5.addWidget(self.tanggal_1)
        self.tanggal_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.tanggal_2.setMinimumSize(QtCore.QSize(100, 50))
        self.tanggal_2.setMaximumSize(QtCore.QSize(100, 50))
        self.tanggal_2.setObjectName("tanggal_2")
        self.HLayout_5.addWidget(self.tanggal_2)
        self.tanggal_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.tanggal_3.setMinimumSize(QtCore.QSize(100, 50))
        self.tanggal_3.setMaximumSize(QtCore.QSize(100, 50))
        self.tanggal_3.setObjectName("tanggal_3")
        self.HLayout_5.addWidget(self.tanggal_3)
        self.tanggal_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.tanggal_4.setMinimumSize(QtCore.QSize(100, 50))
        self.tanggal_4.setMaximumSize(QtCore.QSize(100, 50))
        self.tanggal_4.setObjectName("tanggal_4")
        self.HLayout_5.addWidget(self.tanggal_4)
        self.tanggal_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.tanggal_5.setMinimumSize(QtCore.QSize(100, 49))
        self.tanggal_5.setMaximumSize(QtCore.QSize(100, 50))
        self.tanggal_5.setObjectName("tanggal_5")
        self.HLayout_5.addWidget(self.tanggal_5)
        self.label_tanggaltayang = QtWidgets.QLabel(self.frame_3)
        self.label_tanggaltayang.setGeometry(QtCore.QRect(30, 10, 201, 31))
        self.label_tanggaltayang.setStyleSheet("background: none;")
        self.label_tanggaltayang.setObjectName("label_tanggaltayang")
        self.bg_hijau1 = QtWidgets.QLabel(self.frame_3)
        self.bg_hijau1.setGeometry(QtCore.QRect(20, 10, 221, 31))
        self.bg_hijau1.setStyleSheet("background-color: rgb(0, 165, 132);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"")
        self.bg_hijau1.setText("")
        self.bg_hijau1.setObjectName("bg_hijau1")
        self.label_waktutayang = QtWidgets.QLabel(self.frame_3)
        self.label_waktutayang.setGeometry(QtCore.QRect(30, 120, 201, 31))
        self.label_waktutayang.setStyleSheet("background: none;")
        self.label_waktutayang.setObjectName("label_waktutayang")
        self.bg_hijau2 = QtWidgets.QLabel(self.frame_3)
        self.bg_hijau2.setGeometry(QtCore.QRect(20, 120, 221, 31))
        self.bg_hijau2.setStyleSheet("background-color: rgb(0, 165, 132);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"")
        self.bg_hijau2.setText("")
        self.bg_hijau2.setObjectName("bg_hijau2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 150, 701, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.HLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.HLayout_6.setContentsMargins(0, 0, 0, 0)
        self.HLayout_6.setSpacing(3)
        self.HLayout_6.setObjectName("HLayout_6")
        self.jam_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.jam_1.setMinimumSize(QtCore.QSize(100, 50))
        self.jam_1.setMaximumSize(QtCore.QSize(100, 50))
        self.jam_1.setObjectName("jam_1")
        self.HLayout_6.addWidget(self.jam_1)
        self.jam_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.jam_2.setMinimumSize(QtCore.QSize(100, 50))
        self.jam_2.setMaximumSize(QtCore.QSize(100, 50))
        self.jam_2.setObjectName("jam_2")
        self.HLayout_6.addWidget(self.jam_2)
        self.jam_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.jam_3.setMinimumSize(QtCore.QSize(100, 50))
        self.jam_3.setMaximumSize(QtCore.QSize(100, 50))
        self.jam_3.setObjectName("jam_3")
        self.HLayout_6.addWidget(self.jam_3)
        self.jam_4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.jam_4.setMinimumSize(QtCore.QSize(100, 50))
        self.jam_4.setMaximumSize(QtCore.QSize(100, 50))
        self.jam_4.setObjectName("jam_4")
        self.HLayout_6.addWidget(self.jam_4)
        self.jam_5 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.jam_5.setMinimumSize(QtCore.QSize(100, 50))
        self.jam_5.setMaximumSize(QtCore.QSize(100, 50))
        self.jam_5.setObjectName("jam_5")
        self.HLayout_6.addWidget(self.jam_5)
        self.jam_6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.jam_6.setMinimumSize(QtCore.QSize(100, 49))
        self.jam_6.setMaximumSize(QtCore.QSize(100, 50))
        self.jam_6.setObjectName("jam_6")
        self.HLayout_6.addWidget(self.jam_6)
        self.update_tanggal = QtWidgets.QPushButton(self.frame_3)
        self.update_tanggal.setGeometry(QtCore.QRect(260, 10, 81, 31))
        self.update_tanggal.setStyleSheet("background-color: rgb(133, 133, 199);\n"
"font-size: 12px;")
        self.update_tanggal.setObjectName("update_tanggal")
        self.update_waktu = QtWidgets.QPushButton(self.frame_3)
        self.update_waktu.setGeometry(QtCore.QRect(260, 120, 81, 31))
        self.update_waktu.setStyleSheet("background-color: rgb(133, 133, 199);\n"
"font-size: 12px;")
        self.update_waktu.setObjectName("update_waktu")
        self.layoutWidget.raise_()
        self.bg_hijau1.raise_()
        self.label_tanggaltayang.raise_()
        self.bg_hijau2.raise_()
        self.label_waktutayang.raise_()
        self.layoutWidget_2.raise_()
        self.update_tanggal.raise_()
        self.update_waktu.raise_()
        self.import_poster = QtWidgets.QPushButton(self.frame_1)
        self.import_poster.setGeometry(QtCore.QRect(40, 210, 91, 31))
        self.import_poster.setStyleSheet("background-color: rgb(133, 133, 199);\n"
"font-size: 12px;\n"
"border-radius: 10px;")
        self.import_poster.setObjectName("import_poster")
        self.verticalLayout.addWidget(self.frame_1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Absolute Cinema"))
        self.tombol_kembali.setText(_translate("MainWindow", "KEMBALI"))
        self.tombol_save.setText(_translate("MainWindow", "SAVE"))
        self.label_admin.setText(_translate("MainWindow", "ADMIN"))
        self.label_produksi.setText(_translate("MainWindow", "Produksi       :"))
        self.label_sutradara.setText(_translate("MainWindow", "Sutradara     :"))
        self.edit_produksi.setPlaceholderText(_translate("MainWindow", "produksi"))
        self.edit_sutradara.setPlaceholderText(_translate("MainWindow", "sutradara"))
        self.isi_judulfilm.setText(_translate("MainWindow", "Judul_Film"))
        self.label_sinopsis.setText(_translate("MainWindow", "Sinopsis :"))
        self.edit_sinopsis.setPlaceholderText(_translate("MainWindow", "sinopsis"))
        self.label_aktor.setText(_translate("MainWindow", "Aktor           :"))
        self.label_age.setText(_translate("MainWindow", "Age               :"))
        self.edit_aktor.setPlaceholderText(_translate("MainWindow", "aktor"))
        self.edit_age.setPlaceholderText(_translate("MainWindow", "age"))
        self.tanggal_1.setText(_translate("MainWindow", "-"))
        self.tanggal_2.setText(_translate("MainWindow", "-"))
        self.tanggal_3.setText(_translate("MainWindow", "-"))
        self.tanggal_4.setText(_translate("MainWindow", "-"))
        self.tanggal_5.setText(_translate("MainWindow", "-"))
        self.label_tanggaltayang.setText(_translate("MainWindow", "TANGGAL TAYANG"))
        self.label_waktutayang.setText(_translate("MainWindow", "WAKTU TAYANG"))
        self.jam_1.setText(_translate("MainWindow", "-"))
        self.jam_2.setText(_translate("MainWindow", "-"))
        self.jam_3.setText(_translate("MainWindow", "-"))
        self.jam_4.setText(_translate("MainWindow", "-"))
        self.jam_5.setText(_translate("MainWindow", "-"))
        self.jam_6.setText(_translate("MainWindow", "-"))
        self.update_tanggal.setText(_translate("MainWindow", "Update"))
        self.update_waktu.setText(_translate("MainWindow", "Update"))
        self.import_poster.setText(_translate("MainWindow", "Import"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
