# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Update_film.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ico.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding:0 ;\n"
"    margin:0 ;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: ;\n"
"    background-image: url(:/images/1a800x6001.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.navbar = QtWidgets.QFrame(self.centralwidget)
        self.navbar.setMinimumSize(QtCore.QSize(750, 50))
        self.navbar.setMaximumSize(QtCore.QSize(800, 50))
        self.navbar.setStyleSheet("\n"
"QFrame#navbar {\n"
"    background-color: #1e1e2f;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  rgb(220, 165, 50);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"}\n"
"")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.HLayout_3 = QtWidgets.QHBoxLayout()
        self.HLayout_3.setObjectName("HLayout_3")
        self.tombol_kembali = QtWidgets.QPushButton(self.navbar)
        self.tombol_kembali.setMinimumSize(QtCore.QSize(50, 50))
        self.tombol_kembali.setObjectName("tombol_kembali")
        self.HLayout_3.addWidget(self.tombol_kembali)
        self.icon_vline = QtWidgets.QLabel(self.navbar)
        self.icon_vline.setMinimumSize(QtCore.QSize(20, 35))
        self.icon_vline.setMaximumSize(QtCore.QSize(20, 35))
        self.icon_vline.setText("")
        self.icon_vline.setPixmap(QtGui.QPixmap(":/icons/icons8-line-100.png"))
        self.icon_vline.setScaledContents(True)
        self.icon_vline.setObjectName("icon_vline")
        self.HLayout_3.addWidget(self.icon_vline)
        self.label_home = QtWidgets.QPushButton(self.navbar)
        self.label_home.setMinimumSize(QtCore.QSize(50, 50))
        self.label_home.setObjectName("label_home")
        self.HLayout_3.addWidget(self.label_home)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.HLayout_3.addItem(spacerItem)
        self.label_admin = QtWidgets.QPushButton(self.navbar)
        self.label_admin.setMinimumSize(QtCore.QSize(50, 50))
        self.label_admin.setObjectName("label_admin")
        self.HLayout_3.addWidget(self.label_admin)
        self.horizontalLayout_4.addLayout(self.HLayout_3)
        self.verticalLayout.addWidget(self.navbar)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLabel{  \n"
"      font-family: \"Segoe UI\";\n"
"    font-size: 9pt;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_comingsoon = QtWidgets.QLabel(self.frame)
        self.label_comingsoon.setGeometry(QtCore.QRect(26, 272, 191, 31))
        self.label_comingsoon.setObjectName("label_comingsoon")
        self.label_nowplaying = QtWidgets.QLabel(self.frame)
        self.label_nowplaying.setGeometry(QtCore.QRect(30, 10, 181, 31))
        self.label_nowplaying.setObjectName("label_nowplaying")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(-1, 29, 781, 201))
        self.frame_2.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 35px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-clip: border;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 776, 191))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.HLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.HLayout_2.setContentsMargins(0, 0, 0, 0)
        self.HLayout_2.setObjectName("HLayout_2")
        self.isi_poster1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster1.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster1.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster1.setObjectName("isi_poster1")
        self.HLayout_2.addWidget(self.isi_poster1)
        self.isi_poster2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster2.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster2.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster2.setObjectName("isi_poster2")
        self.HLayout_2.addWidget(self.isi_poster2)
        self.isi_poster3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster3.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster3.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster3.setObjectName("isi_poster3")
        self.HLayout_2.addWidget(self.isi_poster3)
        self.isi_poster4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster4.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster4.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster4.setObjectName("isi_poster4")
        self.HLayout_2.addWidget(self.isi_poster4)
        self.isi_poster5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.isi_poster5.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster5.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster5.setObjectName("isi_poster5")
        self.HLayout_2.addWidget(self.isi_poster5)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(-1, 299, 781, 191))
        self.frame_3.setStyleSheet("QLabel {\n"
"    border: 1px solid black;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 35px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-clip: border;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, -11, 776, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HLayout_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HLayout_1.setContentsMargins(0, 0, 0, 0)
        self.HLayout_1.setObjectName("HLayout_1")
        self.isi_poster6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster6.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster6.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster6.setObjectName("isi_poster6")
        self.HLayout_1.addWidget(self.isi_poster6)
        self.isi_poster7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster7.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster7.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster7.setObjectName("isi_poster7")
        self.HLayout_1.addWidget(self.isi_poster7)
        self.isi_poster8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster8.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster8.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster8.setObjectName("isi_poster8")
        self.HLayout_1.addWidget(self.isi_poster8)
        self.isi_poster9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster9.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster9.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster9.setObjectName("isi_poster9")
        self.HLayout_1.addWidget(self.isi_poster9)
        self.isi_poster10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.isi_poster10.setMinimumSize(QtCore.QSize(150, 170))
        self.isi_poster10.setMaximumSize(QtCore.QSize(150, 170))
        self.isi_poster10.setObjectName("isi_poster10")
        self.HLayout_1.addWidget(self.isi_poster10)
        self.bg_hijau1 = QtWidgets.QLabel(self.frame)
        self.bg_hijau1.setGeometry(QtCore.QRect(0, 10, 221, 31))
        self.bg_hijau1.setStyleSheet("background-color: rgb(0, 165, 132);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"")
        self.bg_hijau1.setText("")
        self.bg_hijau1.setObjectName("bg_hijau1")
        self.bg_hijau2 = QtWidgets.QLabel(self.frame)
        self.bg_hijau2.setGeometry(QtCore.QRect(0, 270, 221, 31))
        self.bg_hijau2.setStyleSheet("background-color: rgb(0, 165, 132);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"")
        self.bg_hijau2.setText("")
        self.bg_hijau2.setObjectName("bg_hijau2")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(0, 210, 791, 61))
        self.frame_4.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"    font: 63 9pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.HLayout_5 = QtWidgets.QHBoxLayout()
        self.HLayout_5.setObjectName("HLayout_5")
        self.update1 = QtWidgets.QPushButton(self.frame_4)
        self.update1.setObjectName("update1")
        self.HLayout_5.addWidget(self.update1)
        self.delete1 = QtWidgets.QPushButton(self.frame_4)
        self.delete1.setObjectName("delete1")
        self.HLayout_5.addWidget(self.delete1)
        self.update2 = QtWidgets.QPushButton(self.frame_4)
        self.update2.setObjectName("update2")
        self.HLayout_5.addWidget(self.update2)
        self.delete2 = QtWidgets.QPushButton(self.frame_4)
        self.delete2.setObjectName("delete2")
        self.HLayout_5.addWidget(self.delete2)
        self.update3 = QtWidgets.QPushButton(self.frame_4)
        self.update3.setObjectName("update3")
        self.HLayout_5.addWidget(self.update3)
        self.delete3 = QtWidgets.QPushButton(self.frame_4)
        self.delete3.setObjectName("delete3")
        self.HLayout_5.addWidget(self.delete3)
        self.update4 = QtWidgets.QPushButton(self.frame_4)
        self.update4.setObjectName("update4")
        self.HLayout_5.addWidget(self.update4)
        self.delete4 = QtWidgets.QPushButton(self.frame_4)
        self.delete4.setObjectName("delete4")
        self.HLayout_5.addWidget(self.delete4)
        self.update5 = QtWidgets.QPushButton(self.frame_4)
        self.update5.setObjectName("update5")
        self.HLayout_5.addWidget(self.update5)
        self.delete5 = QtWidgets.QPushButton(self.frame_4)
        self.delete5.setObjectName("delete5")
        self.HLayout_5.addWidget(self.delete5)
        self.horizontalLayout_7.addLayout(self.HLayout_5)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 460, 791, 81))
        self.frame_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.511364, stop:0 rgba(255, 153, 51, 255), stop:1 rgba(252, 239, 145, 255));\n"
"    color: rgb(63, 63, 63);\n"
"    font-weight: bold;\n"
"    border: 1px solid rgb(254, 175, 75) ;\n"
"    border-radius: 8px;\n"
"    padding: 4px 10px;\n"
"    font: 63 9pt \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     /* Warna saat hover */\n"
"    background-color: rgb(255, 155, 53);\n"
"    color: white;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.HLayout_6 = QtWidgets.QHBoxLayout()
        self.HLayout_6.setObjectName("HLayout_6")
        self.update6 = QtWidgets.QPushButton(self.frame_5)
        self.update6.setObjectName("update6")
        self.HLayout_6.addWidget(self.update6)
        self.delete6 = QtWidgets.QPushButton(self.frame_5)
        self.delete6.setObjectName("delete6")
        self.HLayout_6.addWidget(self.delete6)
        self.update7 = QtWidgets.QPushButton(self.frame_5)
        self.update7.setObjectName("update7")
        self.HLayout_6.addWidget(self.update7)
        self.delete7 = QtWidgets.QPushButton(self.frame_5)
        self.delete7.setObjectName("delete7")
        self.HLayout_6.addWidget(self.delete7)
        self.update8 = QtWidgets.QPushButton(self.frame_5)
        self.update8.setObjectName("update8")
        self.HLayout_6.addWidget(self.update8)
        self.delete8 = QtWidgets.QPushButton(self.frame_5)
        self.delete8.setObjectName("delete8")
        self.HLayout_6.addWidget(self.delete8)
        self.update9 = QtWidgets.QPushButton(self.frame_5)
        self.update9.setObjectName("update9")
        self.HLayout_6.addWidget(self.update9)
        self.delete9 = QtWidgets.QPushButton(self.frame_5)
        self.delete9.setObjectName("delete9")
        self.HLayout_6.addWidget(self.delete9)
        self.update10 = QtWidgets.QPushButton(self.frame_5)
        self.update10.setObjectName("update10")
        self.HLayout_6.addWidget(self.update10)
        self.delete10 = QtWidgets.QPushButton(self.frame_5)
        self.delete10.setObjectName("delete10")
        self.HLayout_6.addWidget(self.delete10)
        self.horizontalLayout_8.addLayout(self.HLayout_6)
        self.bg_hijau2.raise_()
        self.bg_hijau1.raise_()
        self.label_nowplaying.raise_()
        self.label_comingsoon.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MAbsolute Cinema"))
        self.tombol_kembali.setText(_translate("MainWindow", "KEMBALI"))
        self.label_home.setText(_translate("MainWindow", "HOME"))
        self.label_admin.setText(_translate("MainWindow", "ADMIN"))
        self.label_comingsoon.setText(_translate("MainWindow", "COMING SOON"))
        self.label_nowplaying.setText(_translate("MainWindow", "NOW PLAYING"))
        self.isi_poster1.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster2.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster3.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster4.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster5.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster6.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster7.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster8.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster9.setText(_translate("MainWindow", "TextLabel"))
        self.isi_poster10.setText(_translate("MainWindow", "TextLabel"))
        self.update1.setText(_translate("MainWindow", "Update"))
        self.delete1.setText(_translate("MainWindow", "Delete"))
        self.update2.setText(_translate("MainWindow", "Update"))
        self.delete2.setText(_translate("MainWindow", "Delete"))
        self.update3.setText(_translate("MainWindow", "Update"))
        self.delete3.setText(_translate("MainWindow", "Delete"))
        self.update4.setText(_translate("MainWindow", "Update"))
        self.delete4.setText(_translate("MainWindow", "Delete"))
        self.update5.setText(_translate("MainWindow", "Update"))
        self.delete5.setText(_translate("MainWindow", "Delete"))
        self.update6.setText(_translate("MainWindow", "Update"))
        self.delete6.setText(_translate("MainWindow", "Delete"))
        self.update7.setText(_translate("MainWindow", "Update"))
        self.delete7.setText(_translate("MainWindow", "Delete"))
        self.update8.setText(_translate("MainWindow", "Update"))
        self.delete8.setText(_translate("MainWindow", "Delete"))
        self.update9.setText(_translate("MainWindow", "Update"))
        self.delete9.setText(_translate("MainWindow", "Delete"))
        self.update10.setText(_translate("MainWindow", "Update"))
        self.delete10.setText(_translate("MainWindow", "Delete"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
